### ISSUE TITLE
Can you add new features to your addon?

### ISSUE THREAD

**Issue by Vitoshka** [firenahzku/VGAttackBar#2]
**Change** the width, length of the bar, as well as the ability to reduce, increase and move up and down, left to right, text inside the bar? And also make it possible to select the display in the bar of a two-digit time countdown to the next attack and remove the parentheses?
https://d.radikal.ru/d22/1804/a6/5546358c654e.jpg

**Also** wanted to ask the addon supports the correct time until the next attack when I use: Judgement (and Seal) of the Crusader. **Judgement (and Seal) of the of Command.** Judgement (and Seal) of the of Command. Judgement (and Seal) of the of Righteousness?

_If you manage to make these improvements, then your addon will be ideal_

Txh)

**Comment by firenahzku** [comment]
Hello,

I do not plan to work on cosmetic changes that you suggested, sorry. That is purely a matter of personal taste and anyone can edit those things in the .xml file to make them look the way they want.
